### ISSUE TITLE
Hello, I don't mind report the error on GitHub this time. Thank you for your reply.

### ISSUE THREAD

**Issue by Ayoulydia** [Foxy-null/AnkiCraft#5]
加载⁨AnkiCraft⁩时：
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/__init__.py", line 16, in <module>
    from . import main
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/main.py", line 34, in <module>
    from .controllers import (
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/controllers.py", line 13, in <module>
    from . import leaderboards
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/leaderboards.py", line 12, in <module>
    from .persistence import PersistedAchievement, min_datetime
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/persistence.py", line 6, in <module>
    from ._vendor.yoyo import get_backend
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/__init__.py", line 27, in <module>
    from .connections import get_backend
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/connections.py", line 23, in <module>
    from .migrations import default_migration_table
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/migrations.py", line 44, in <module>
    from .utils import plural
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/utils.py", line 23, in <module>
    from .config import CONFIG_EDITOR_KEY
  File "/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/config.py", line 19, in <module>
    from .. import iniherit
ImportError: cannot import name 'iniherit' from '368161874._vendor' (/Users/youyoulydia/Library/Application Support/Anki2/addons21/368161874/_vendor/__init__.py)

**Comment by Foxy-null** [comment]
Thank you for your cooperation! I have released a [new version](https://github.com/Foxy-null/AnkiCraft/releases/tag/v1.1.1) and would appreciate it if you could let me know if there were any errors after the update.

**Comment by Foxy-null** [comment]
( Notes: duplicate of #4 )

**Comment by Foxy-null** [comment]
Duplicate of #4

**Comment by Amr0100700** [comment]
Version ⁨2.1.66 (70506aeb)⁩

Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨AnkiCraft⁩':
⁨Traceback (most recent call last):
File "aqt.addons", line 246, in loadAddons
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_init_.py", line 16, in
from . import main
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\main.py", line 34, in
from .controllers import (
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\controllers.py", line 13, in
from . import leaderboards
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\leaderboards.py", line 12, in
from .persistence import PersistedAchievement, min_datetime
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874\persistence.py", line 6, in
from .vendor.yoyo import get_backend
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_vendor\yoyo_init.py", line 27, in
from .connections import get_backend
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_vendor\yoyo\connections.py", line 23, in
from .migrations import default_migration_table
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_vendor\yoyo\migrations.py", line 44, in
from .utils import plural
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_vendor\yoyo\utils.py", line 23, in
from .config import CONFIG_EDITOR_KEY
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_vendor\yoyo\config.py", line 19, in
from .. import iniherit
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_vendor\iniherit_init_.py", line 9, in
from .parser import *
File "C:\Users\Lenovo\AppData\Roaming\Anki2\addons21\368161874_vendor\iniherit\parser.py", line 14, in
from six.moves import configparser as CP
ModuleNotFoundError: No module named 'six'

**Comment by Foxy-null** [comment]
Hi @Amr0100700. Thank you for reporting an issue!

Have you updated AnkiCraft to latest version?

I just released an update a while ago, so the latest version may not be applied unless you manually check for updates from the add-ons menu.

Sorry for the inconvenience.

**Comment by Amr0100700** [comment]
I have updated AnkiCraft to latest version but I still have the same error

this addon doesn't work on my device but AnkiCraft looks great and thank you for your hard work ❤️

**Comment by Foxy-null** [comment]
I'm glad you like the add-on! Thanks!
Unfortunately, I'm out of town, so I'll have to stare at the code again when I get home.
Sorry for taking so long.

**Comment by Foxy-null** [comment]
## I've released the [v1.1.2](https://github.com/Foxy-null/AnkiCraft/releases/tag/v1.1.2) update!
This time I checked both MacOS and Windows environments, so it should be fine...! (not sure about that for a second though)
![Screenshot 2023-10-01 224014](https://github.com/Foxy-null/AnkiCraft/assets/72304646/af95e13a-b3d1-4cb9-ae30-a5caa4f379b2)
Please let me know whether this update caused any error!

Thank you all for your patience and support!!!

**Comment by Amr0100700** [comment]
It works now 
thank you so much ❤️

**Comment by Foxy-null** [comment]
Yeah!!! Finally we did it!!
Enjoy playing AnkiCraft!

**Comment by Foxy-null** [comment]
Yeah!!! Finally we did it!!
Enjoy playing AnkiCraft!
